### ISSUE TITLE
Warning in .Net 6/7

### ISSUE THREAD

**Issue by lisheng51** [tasos-py/AES-Encryption-Classes#10]
This is very practical, can it enhance compatibility?

**Comment by tasos-py** [comment]
I just ran AesEncryption.cs in .Net6, without any compiler warnings. Could you give me more details? Also, I'm not sure what you mean by "enhance compatibility", please clarify that

**Comment by lisheng51** [comment]
Warning	SYSLIB0022	'RijndaelManaged' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead
