### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [tasos-py/AES-Encryption-Classes#6]

**Comment by maholaca522** [comment]
.cpp

std::string data = "123456";
    std::string password = "my super strong password";
    AesEncryption aes("cbc", 256);
    CryptoPP::SecByteBlock enc = aes.encrypt(data, password);
------------------------------------------------------------------------------------------------------------------
.php

$data = "g7yZgoPQifpCWIsWstWQ1+a4VwUYoKZjD6eVvDLc0/dhyjG49ThLCojl9OWObN7zooW7eS5KLup3sKjAPldyqCz0oEt5gYohyWnpqV9FUQA=";
$password = "my super strong password";
$aes = new AesEncryption();
$dec = $aes->decrypt($data, $password);

echo $dec;
